spring.application.name=LMS_Project

# Configuración de PostgreSQL para Docker (Testcontainers)
spring.datasource.url=jdbc:tc:postgresql:16-alpine:///LMS_BDD
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
